### ISSUE TITLE
undefined reference to symbol 'glBlendFunc'

### ISSUE THREAD

**Issue by zhanhe18** [plumonito/dtslam#1]
Hi , I am executed the cmake command and got makefile .
When the make almost done . it throw out two errors . 

/usr/bin/ld: ../dtslam_ui/libdtslam_ui.a(TextRenderer.cpp.o): undefined reference to symbol 'glBlendFunc'
//usr/lib/libGL.so.1: error adding symbols: DSO missing from command line

It says I am undefined reference to symbol glBlendFunc , but this function is in libGL , I have this lib , I try make this all day , have any ideas ? Thanks .

**Comment by zhanhe18** [comment]
Solved.

**Comment by AdithyaPediredla** [comment]
How did you solve it?
