### ISSUE TITLE
Mac Osx compilation fails

### ISSUE THREAD

**Issue by ghost** [plumonito/dtslam#3]
Hi,

Hope you are doing well !

I was checking DTSLAM but the compilation on OSX fails. Do u have an updated version of the CMakeLists for OSX by any chance ?

Thanks in advance.

Cheers,
Luc

**Comment by plumonito** [comment]
Hi, sorry, never tested it for Mac. Windows was the main dev environment.

**Comment by sunstarchan** [comment]
@plumonito 

is there any detailed document about how to run examples? 

Thanks

**Comment by plumonito** [comment]
There is no detailed document. It should be straightforward though, download, cmake, build, run.

**Comment by sunstarchan** [comment]
@plumonito 
which platform? Ubuntu, or Windows 32-bit with MinGW?

**Comment by plumonito** [comment]
Odd options. My main development environment was MSVC on Windows. Though it used to compile on Ubuntu as well.

**Comment by kihwan23** [comment]
The code was only tested under MSVC and Ubuntu as you can see in cmake setting. BTW, we will make it clear on the readme file soon. The actual build process is pretty straightforward.

**Comment by sunstarchan** [comment]
Thanks all of you. I've run it successfully on Ubuntu. It's a amazing SLAM system. 

BTW, is there a way to show the camera trajectory?
