### ISSUE TITLE
findEssentialMat and recoverPose

### ISSUE THREAD

**Issue by ShuangLiu1992** [plumonito/dtslam#4]
Dear contributors,

It seems that opencv now supports findEssentialMat with ransac and they have their own recoverPose that validates the essential mat by doing cheirality check, has this been tested in your project? Have they fixed the problem of producing invalid essential matrix?

Thanks!

**Comment by sunstarchan** [comment]
@ShuangLiu1992 

could you share the detailed steps to setup the build environment? and How to build the project?

Thanks

**Comment by plumonito** [comment]
@ShuangLiu1992 the opencv version included in this project already had a findEssentialMat. We implemented our own ransac and cheirality checks.

@sunstarchan I just updated the build system to work with ubuntu 16.04.
