### ISSUE TITLE
Setup environment Linux

### ISSUE THREAD

**Issue by xav12358** [plumonito/dtslam#6]
Hello,
I work on linux 16.04 and I would like to execute the dtslam on it.
I can setup the cmakefil on th main folder. Here is the message I get:
`CMake Error at 3rdparty/CMakeLists.txt:61 (file):
  file STRINGS file
  "/home/cyclopus/Bureau/Developpement/SLAM/dtslam-master/3rdparty/usr/lib/cmake/gflags/gflags-config.cmake"
  cannot be read.

CMake Error at CMakeLists.txt:13 (find_package):
  Could not find a package configuration file provided by "freeglut" with any
  of the following names:

    freeglutConfig.cmake
    freeglut-config.cmake

  Add the installation prefix of "freeglut" to CMAKE_PREFIX_PATH or set
  "freeglut_DIR" to a directory containing one of the above files.  If
  "freeglut" provides a separate development package or SDK, be sure it has
  been installed.
`

Where is the instruction to setup?

**Comment by plumonito** [comment]
I've pushed a couple of small commits to update the build environment. It works for me on 16.04 out of the box now.

**Comment by xav12358** [comment]
Thank you now it start compiling but I get that:
```
 CMake Error at 3rdparty/cmake/config_external_project.cmake:100 (message):
   Error building Eigen: 2
 Call Stack (most recent call first):
   3rdparty/CMakeLists.txt:107 (ConfigExternalProject)
```

**Comment by plumonito** [comment]
The cmkae build system doesn't give the most helpful error messages. I think you can find the build log in "build_dir/3rdparty/Eigen/build_output.txt" or something like that. That might help you debug the problem.

**Comment by xav12358** [comment]
Here is the error I get:
`abort: repository /home/cc/Bureau/Developpement/SLAM/dtslam-master/3rdparty/eigen-3.2.2 not found!
abort: repository /home/cc/Bureau/Developpement/SLAM/dtslam-master/3rdparty/eigen-3.2.2 not found!
CMake Warning at blas/CMakeLists.txt:32 (message):
   No fortran compiler has been detected, the blas build will be incomplete.


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "openglsupport" in directory /home/cc/Bureau/Developpement/SLAM/dtslam-master/3rdparty/eigen-3.2.2/unsupported/test

make[2]: *** [src/Eigen-stamp/Eigen-configure] Erreur 1
make[1]: *** [CMakeFiles/Eigen.dir/all] Erreur 2
make: *** [all] Erreur 2`

I don't understand because the folder exist.

**Comment by plumonito** [comment]
Perhaps solve the other problems first. Install the glut xmu library and a fortran compiler.

**Comment by xav12358** [comment]
It works properly now.
Thank you for the new feature.
