### ISSUE TITLE
Access to datasets?

### ISSUE THREAD

**Issue by NikolausDemmel** [plumonito/dtslam#9]
Interesting work! Are the dataset you evaluate on in the paper, i.e. City of Sights from Gruber also the video from Pirchheim et. al available somewhere?

**Comment by plumonito** [comment]
City of Sights is easy to find (https://arbook.icg.tugraz.at/schmalstieg/Schmalstieg_188.pdf). The Pirchheim et. al video might be a bit harder. Maybe I got it directly from the author himself. Not sure though. But I don't have it anymore.

**Comment by NikolausDemmel** [comment]
Thanks for the quick reply!

Sorry about City of Sights, somehow I screwed up when looking for it. Should have found it myself...

I sent the Pirchheim et. al an email about their video. Let's see.

**Comment by NikolausDemmel** [comment]
In case someone else is looking for it here, Christian kindly replied with a link:

>>I was wondering if the video you used in your publication "Handling pure camera rotation in keyframe-based SLAM” from ISMAR 2013 is available somewhere?
> 
> Here you are:
> https://www.tianpi.org/papers/2013-ISMAR-Dataset.zip
> The archive contains a README.
> If you have any questions please come back to me.
